services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable
    container_name: watchtower
  express-app:
    image: apopat/express-app
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"